apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: left-vn
  namespace: contrail
  annotations:
    "opencontrail.org/cidr" : "14.14.14.0/24"
    "opencontrail.org/ip_fabric_snat" : "false"
    "opencontrail.org/ip_fabric_forwarding" : "false"
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "contrail-k8s-cni"
}'