apiVersion: v1
kind: Pod
metadata:
  name: left-ubuntu-pod
  labels:
    app: webapp-sc
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        { "name": "left-network" }]'
spec:
  containers:
    - name: ubuntu-left-pod-sc
      image: ubuntu
      securityContext:
          privileged: true
          capabilities:
           add:
             - NET_ADMIN