apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: right
  annotations:
    opencontrail.org/cidr: "5.4.3.0/24"
spec:
  config: '{ cniVersion: "0.3.0", type: "contrail-k8s-cni" }'
---
apiVersion: v1
kind: Pod
metadata:
  name: right-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[ { "name": "right" } ]'
spec:
  containers:
  - image: ubuntu
    name: right-container
