apiVersion: v1
kind: Pod
metadata:
  name: right-ubuntu-pod
  labels:
    app: webapp-sc
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        { "name": "right-network" }]'
spec:
  containers:
    - name: ubuntu-right-pod-sc
      image: ubuntu
      command: ["/sbin/init"]
      securityContext:
          privileged: true
          capabilities:
           add:
             - NET_ADMIN