apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ns1
spec:
  selector:
    matchLabels:
      app: http_test
  template:
    metadata:
      labels:
        app: http_test
    spec:
      containers:
      - name: nginx-pod
        image: nginx
  replicas: 2