apiVersion: v1
kind: Service
metadata:
  name: ctest-nginx-svc-56797998
  namespace: ctest-namespace-41847719
spec:
  clusterIP: 10.108.118.92
  externalIPs:
  - 10.204.219.204
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: http_test
  sessionAffinity: None
  type: ClusterIP
