apiVersion: v1
kind: Service
metadata:
  name: ctest-nginx-svc-56797998
  namespace: ns1
spec:
  clusterIP: 10.97.235.203
  externalIPs:
  - 10.204.220.196
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: http_test
  sessionAffinity: None
  type: ClusterIP
