apiVersion: apps/v1
kind: Deployment
metadata:
  name: cirros-deployment
spec:
  selector:
    matchLabels:
      app: cirros-deployment
  template:
    metadata:
      labels:
        app: cirros-deployment
    spec:
      containers:
      - name: cirros-pod
        image: cirros
  replicas: 4