apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubu2-deployment
spec:
  selector:
    matchLabels:
      app: ubu2-deployment
  template:
    metadata:
      labels:
        app: ubu2-deployment
    spec:
      containers:
      - name: ubuntu-pod
        image: ubuntu
        command: ["sleep", "123456"]
  replicas: 4